
import { Metadata } from "next"

export const metadata = {
  title: {
    default:'This is a default title',
    template:'%s | template works'
  },
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <header style={{backgroundColor:'lightblue',padding:'1rem'}}>Header</header>
        {children}
        <footer  style={{backgroundColor:'gostwhite',padding:'1rem'}}>Footter</footer>
        </body>
    </html>
  )
}
